### ISSUE TITLE
Overflow Error

### ISSUE THREAD

**Issue by 123hacker321** [mkorman90/regipy#88] opened 2020-07-19 13:42 UTC
for entry in reg.recurse_subkeys(as_json=True):
...     print(entry)
...
Subkey(subkey_name='1024', path='\\Apple Computer, Inc.\\iPod\\RegisteredApps\\1024', timestamp='2020-07-13T12:11:12.411520+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='RegisteredApps', path='\\Apple Computer, Inc.\\iPod\\RegisteredApps', timestamp='2020-07-13T12:19:31.697374+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='RegisteredApps', path='\\Apple Computer, Inc.\\iPod\\RegisteredApps', timestamp='2020-07-13T12:19:31.697374+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='iPod', path='\\Apple Computer, Inc.\\iPod', timestamp='2020-07-13T12:19:31.735122+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='iPod', path='\\Apple Computer, Inc.\\iPod', timestamp='2020-07-13T12:19:31.735122+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='Apple Computer, Inc.', path='\\Apple Computer, Inc.', timestamp='2020-07-13T12:19:31.697374+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='Apple Computer, Inc.', path='\\Apple Computer, Inc.', timestamp='2020-07-13T12:19:31.697374+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='Apple Application Support', path='\\Apple Inc.\\Apple Application Support', timestamp='2020-07-13T12:23:08.363750+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='Apple Inc.', path='\\Apple Inc.', timestamp='2020-07-13T12:27:09.542870+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='Apple Inc.', path='\\Apple Inc.', timestamp='2020-07-13T12:27:09.542870+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='BlueStacksInstaller', path='\\BlueStacksInstaller', timestamp='2020-03-20T00:10:16.109034+00:00', values_count=2, values=[{'name': 'MachineID', 'value': '2d599309-ecac-4f72-a2fc-a3e20b5cba31', 'value_type': 'REG_SZ', 'is_corrupted': False}, {'name': 'VersionMachineId_4.180.10.9302', 'value': '023aa6fc-0b35-4bbb-89c6-4eafa60f5d11', 'value_type': 'REG_SZ', 'is_corrupted': False}], actual_path=None)
Subkey(subkey_name='Excel.exe', path='\\Classes\\*\\OpenWithList\\Excel.exe', timestamp='2019-03-19T04:55:56.532884+00:00', values_count=0, values=[], actual_path=None)
Subkey(subkey_name='IExplore.exe', path='\\Classes\\*\\OpenWithList\\IExplore.exe', timestamp='2019-03-19T04:55:56.532884+00:00', values_count=0, values=[], actual_path=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 147, in recurse_subkeys
    yield from self.recurse_subkeys(nk_record=subkey,
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 147, in recurse_subkeys
    yield from self.recurse_subkeys(nk_record=subkey,
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 147, in recurse_subkeys
    yield from self.recurse_subkeys(nk_record=subkey,
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 154, in recurse_subkeys
    values = [attr.asdict(x) for x in subkey.iter_values(as_json=as_json)]
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 154, in <listcomp>
    values = [attr.asdict(x) for x in subkey.iter_values(as_json=as_json)]
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 416, in iter_values
    value = self.read_value(vk, substream)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\regipy\registry.py", line 365, in read_value
    data = stream.read(vk.data_size)
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by tincho9** [comment] 2020-07-20 10:31
Can you share the registry hive? I've never encountered such issue.

**Comment by c0rs** [comment] 2020-08-18 18:15
Hi! I have the same bug at the same place:
```
Traceback (most recent call last):
  File "..\regipy\registry.py", line 504, in get_values
    return [x for x in self.iter_values(as_json=as_json)]
  File "..\regipy\registry.py", line 504, in <listcomp>
    return [x for x in self.iter_values(as_json=as_json)]
  File "..\regipy\registry.py", line 416, in iter_values
    value = self.read_value(vk, substream)
  File "..\regipy\registry.py", line 365, in read_value
    data = stream.read(vk.data_size)
OverflowError: cannot fit 'int' into an index-sized integer
```
The bug occurs when I try to read REG_BINARY value. Do you still need a hive as example?

**Comment by tincho9** [comment] 2020-08-18 19:47
Yes, It would be really helpful.

**Comment by c0rs** [comment] 2020-08-18 21:33
Here hive, code to reproduce bug (at least on my win7) and traceback
[usb_bluetooth.zip](https://github.com/mkorman90/regipy/files/5092943/usb_bluetooth.zip)
```
from regipy.registry import RegistryHive
USB_HIVE = 'usb_bluetooth.hive'
RKEY_USB_TIME = '\\000650268328\\Properties\\{83da6326-97a6-4088-9453-a1923f573b29}\\00000064\\00000000'
reg_usb = RegistryHive(USB_HIVE)
v = reg_usb.get_key(RKEY_USB_TIME).get_value('Data')
print(v)
```
```
Traceback (most recent call last):
  File "bug_reprod.py", line 5, in <module>
    v = reg_usb.get_key(RKEY_USB_TIME).get_value('Data')
  File "..\regipy\registry.py", line 495, in get_value
    for value in self.iter_values(as_json=as_json):
  File "..\regipy\registry.py", line 416, in iter_values
    value = self.read_value(vk, substream)
  File "..\regipy\registry.py", line 365, in read_value
    data = stream.read(vk.data_size)
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by tincho9** [comment] 2020-08-19 06:13
Are you using a 32bit python version? 
![image](https://user-images.githubusercontent.com/18242935/90598521-dc764200-e1fb-11ea-8ae1-f87f8be74c87.png)
I'll try to get a 32bit python later today my verify my claim.

**Comment by c0rs** [comment] 2020-08-19 08:44
Yes, 32bit. I also checked this code on python 64 and everything is fine for that. It looks like the bug exists only for 32-bit python

**Comment by tincho9** [comment] 2020-08-20 09:49
I'm not sure I have a way to fix that in which you will not get incomplete data... I'm not comfortable with that.

**Comment by tincho9** [comment] 2020-08-31 12:18
I'm closing this issue, as Regipy works as expected in x64.

**Closed by tincho9** 2020-08-31 12:18 UTC
